### ISSUE TITLE
Not working..

### ISSUE THREAD

**Issue by FaNNboii** [Merubokkusu/discord-spam-bots#1]
Hey, its not working for me...

![grafik](https://user-images.githubusercontent.com/16906122/43594300-326d5f92-967a-11e8-8a9d-6844d00c827a.png)

I always get errors like:
![grafik](https://user-images.githubusercontent.com/16906122/43594340-47280202-967a-11e8-8a17-0ed71cb9a428.png)

when i try starting it with python3 i get this error:
![grafik](https://user-images.githubusercontent.com/16906122/43594389-606bb556-967a-11e8-8849-ed1748bb6a7a.png)

when i try to start it with start.py i get this error:
![grafik](https://user-images.githubusercontent.com/16906122/43594461-8f1b65f4-967a-11e8-8db5-0efc6a1e7ef5.png)

any idea?

**Comment by Merubokkusu** [comment]
You should only use start.py when running the bot.
I see in the last picture its using python 2.7 so thats why its not working.

**Comment by FaNNboii** [comment]
yes, but when i start it with python 3.6.6 with the prefix python3 i get this error.
![grafik](https://user-images.githubusercontent.com/16906122/43641585-8f3e52e4-9724-11e8-8e2a-d75a47f80923.png)

**Comment by Merubokkusu** [comment]
Sorry for the late response, I'm checking into it right now.

**Comment by Merubokkusu** [comment]
Try using the config to load tokens, just want to see if it has something to do with the format in "tokens.txt"

**Comment by reckr** [comment]
Just want to let you know that I encounter the same issue, using the config to load tokens @Merubokkusu.

**Comment by reckr** [comment]
I don't get the idea of this, why is it opening a Python shell after choosing the bot?

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/issues/1#issuecomment-410497507

And it's just creating a new instance of python for each token.

**Comment by Merubokkusu** [comment]
Actually I didnt fully read your problem, it could be that you have python 2 and 3 installed and since it launches a shell it assumes "python" is python3

**Comment by reckr** [comment]
How do I fix that?

**Comment by Merubokkusu** [comment]
I pushed a new file called start3.py, run that and see if it works

**Comment by sadoj-kuro** [comment]
same here tested with start and start3

**Comment by Merubokkusu** [comment]
> same here tested with start and start3

Whats your error?

**Comment by KuroSenseii** [comment]
`Python 3.4.2 (default, Sep 25 2018, 22:02:39)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Traceback (most recent call last):
  File "start3.py", line 49, in <module>
    p = subprocess.Popen(['python3','bots\server\discord_text_spam.py',token,spam_text,proxy_list[proxy_number]],shell=True)
IndexError: list index out of range
`

**Comment by sadoj-kuro** [comment]
```
Traceback (most recent call last):
  File "start3.py", line 49, in <module>
    p = subprocess.Popen(['python3','bots\server\discord_text_spam.py',token,spam_text,proxy_list[proxy_number]],shell=True)
IndexError: list index out of range
Python 3.4.2 (default, Sep 25 2018, 22:02:39)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
```


i launch with python3.6 for the 3.6.5 version but think the script launch all time with 3.4 :\

i have edited the file for switch python3 for python3.6 and same error but now showing right version

```
Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Traceback (most recent call last):
  File "start3.py", line 49, in <module>
    p = subprocess.Popen(['python3.6','bots\server\discord_text_spam.py',token,spam_text,proxy_list[proxy_number]],shell=True)
IndexError: list index out of range
```

**Comment by sadoj-kuro** [comment]
no soluce ???

**Comment by Merubokkusu** [comment]
Can you gfive me the full log?

**Comment by sadoj-kuro** [comment]
`root@Kuro /home/bot/Discord-Spammer > python3.6 start3.py
EDIT YOUR CONFIG.PY BEFORE USING!
-=Using tokens.txt=-
Type one of the following numbers to launch that spammmer
       +========-Server Spammers-=========+
1 : Text Spammer - Write your own text to spam
2 : Image Spammer - Spam random images in a selected folder
3 : Insult Spammer - Picks insults offline and spams them
         +========-DM Spammers-=========+
4 : Text Spammer - Write your own text to spam
5 : Image Spammer - Spam random images in a selected folder
6 : Insult Spammer - Picks insults offline and spams them
           +========-Other-=========+
0 : Join Server - Join the server thats written in the config
Select a bot: 1
Write spam text : test
Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Traceback (most recent call last):
  File "start3.py", line 49, in <module>
    p = subprocess.Popen(['python3.6','bots\server\discord_text_spam.py',token,spam_text,proxy_list[proxy_number]],shell=True)
IndexError: list index out of range
root@Kuro /home/bot/Discord-Spammer >

`

**Comment by sadoj-kuro** [comment]
only have this ...

**Comment by Merubokkusu** [comment]
My bad, fixed.
https://github.com/Merubokkusu/discord-spam-bots/commit/5343b9b34d7cd51aa1ae4af80398727470cb1b98

**Comment by sadoj-kuro** [comment]
no one error now but no working, nothing happens, the accounts do not spam just console spam the message type help

`root@Kuro /home/bot/Discord-Spammer > python3.6 start.py
EDIT YOUR CONFIG.PY BEFORE USING!
-=Using tokens.txt=-
Type one of the following numbers to launch that spammmer
       +========-Server Spammers-=========+
1 : Text Spammer - Write your own text to spam
2 : Image Spammer - Spam random images in a selected folder
3 : Insult Spammer - Picks insults offline and spams them
         +========-DM Spammers-=========+
4 : Text Spammer - Write your own text to spam
5 : Image Spammer - Spam random images in a selected folder
6 : Insult Spammer - Picks insults offline and spams them
           +========-Other-=========+
0 : Join Server - Join the server thats written in the config
Select a bot: 1
127.0.0.1
Write spam text : test
Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ^C
`

**Comment by Merubokkusu** [comment]
Woops, put the wrong thing lol
https://github.com/Merubokkusu/discord-spam-bots/commit/e3d0518ae2041693a437a72e93bd63f77b39d91e

**Comment by sadoj-kuro** [comment]
nothing happens, the account is connected but no message

`root@Kuro /home/bot/Discord-Spammer > python3.6 start.py
EDIT YOUR CONFIG.PY BEFORE USING!
Type one of the following numbers to launch that spammmer
       +========-Server Spammers-=========+
1 : Text Spammer - Write your own text to spam
2 : Image Spammer - Spam random images in a selected folder
3 : Insult Spammer - Picks insults offline and spams them
         +========-DM Spammers-=========+
4 : Text Spammer - Write your own text to spam
5 : Image Spammer - Spam random images in a selected folder
6 : Insult Spammer - Picks insults offline and spams them
           +========-Other-=========+
0 : Join Server - Join the server thats written in the config
Select a bot: 1
localhost
Write spam text : test
Python 3.6.5 (default, Dec 31 2018, 03:48:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
`

**Comment by Merubokkusu** [comment]
Seems to be a linux issue, I'll test it on linux soon.

**Comment by iShabzz102** [comment]
Ty

**Comment by ghost** [comment]
@Merubokkusu, hey there!

**Have you got any updates on why this isn't working?** I've tried a couple times now and as I can see I've read all of above.

**Comment by Merubokkusu** [comment]
Yeah, its because of how I pass the arguments.
I should have fix by the end of the day.

**Comment by ghost** [comment]
Alright, nice to hear
Have a good day

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/commit/6e14cc1c9af79ed4deb6eba3d3afc6c726cb697b

All of the spammers currently work but the image spammer and auto server joining, I'll add them within a day. 

Make sure your pythonCommand is set to whatever you use to call the python command
https://github.com/Merubokkusu/discord-spam-bots/commit/a52c0bef3adfc2da344769a36243700d7fd1dfa8

**Comment by ghost** [comment]
Alright, I'll see if it does
nice, works

**Comment by TypicallyShad** [comment]
Works perfectly but the join server thing needs https://sites.google.com/a/chromium.org/chromedriver/home or something which I hoped it was the last thing to install, if you could also add a stop command for Linux or something or like it tells you how long to do it

**Comment by iShabzz102** [comment]
does it work for linux

**Comment by iShabzz102** [comment]
doesnt work got this error 
EDIT YOUR CONFIG.PY BEFORE USING!
Type one of the following numbers to launch that spammmer
       +========-Server Spammers-=========+
1 : Text Spammer - Write your own text to spam
2 : Image Spammer - Spam random images in a selected folder
3 : Insult Spammer - Picks insults offline and spams them
         +========-DM Spammers-=========+      
4 : Text Spammer - Write your own text to spam
5 : Image Spammer - Spam random images in a selected folder
6 : Insult Spammer - Picks insults offline and spams them
           +========-Other-=========+
0 : Join Server - Join the server thats written in the config
Select a bot: 1
Write spam text : g
  File "bots/server/discord_text_spam.py", line 25
    async def on_ready():
        ^
SyntaxError: invalid syntax
(xenial)shabzz102@localhost:~/Downloads/discord-spam-bots-master$

**Comment by iShabzz102** [comment]
os ; linux
So it only sent the message once 
Write spam text : gfj
Started Text Spam
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bots/server/discord_text_spam.py", line 42, in on_ready
    print(client.user.name + ' sent ' + spam_text)
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f382' in position 10: ordinal not in range(128)

**Comment by Merubokkusu** [comment]
It's because you're running python 3.5 which doesn't support some Unicode, use python 3.6.4

**Comment by ghost** [comment]
oof

**Comment by sadoj-kuro** [comment]
Select a bot: 0
Starting Server Join
Traceback (most recent call last):
  File "bots/misc/joinServer.py", line 36, in <module>
    browser = webdriver.Chrome('resources/webdrivers/chromedriver-linux',chrome_options=chromeOptions)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service resources/webdrivers/chromedriver-linux unexpectedly exited. Status code was: 127

**Comment by Merubokkusu** [comment]
> Select a bot: 0
> Starting Server Join
> Traceback (most recent call last):
> File "bots/misc/joinServer.py", line 36, in 
> browser = webdriver.Chrome('resources/webdrivers/chromedriver-linux',chrome_options=chromeOptions)
> File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in **init**
> self.service.start()
> File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 98, in start
> self.assert_process_still_running()
> File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
> % (self.path, return_code)
> selenium.common.exceptions.WebDriverException: Message: Service resources/webdrivers/chromedriver-linux unexpectedly exited. Status code was: 127

Server join isn't implemented for linux yet.

EDIT: Actually try running `sudo apt-get install -y chromium-browser`

If that doesnt work try `apt-get install -y libglib2.0-0=2.50.3-2 \
    libnss3=2:3.26.2-1.1+deb9u1 \
    libgconf-2-4=3.2.6-4+b1 \
    libfontconfig1=2.11.0-6.7+b1`

**Comment by sadoj-kuro** [comment]
apt-get install -y chromium-browser
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Package chromium-browser is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'chromium-browser' has no installation candidate

-------------------------------------------------------

apt-get install -y libglib2.0-0=2.50.3-2 \ libnss3=2:3.26.2-1.1+deb9u1 \ libgconf-2-4=3.2.6-4+b1 \ libfontconfig1=2.11.0-6.7+b1
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
E: La version « 2.50.3-2 » de « libglib2.0-0 » n'a pu être trouvée
E: Impossible de trouver le paquet  libnss3
E: Impossible de trouver le paquet  libgconf-2-4
E: Impossible de trouver le paquet  libfontconfig1

I'm running debian 8 on VPS

**Comment by Merubokkusu** [comment]
`sudo add-apt-repository ppa:chromium-daily/ppa && sudo apt-get update`

Then try `sudo apt-get install chromium-browser`

Actually anyway you can install chrome could work.
