### ISSUE TITLE
insultgenerator 🅱️roke

### ISSUE THREAD

**Issue by Technoturnovers** [Merubokkusu/discord-spam-bots#1]
FIX IT FIX IT REEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Merubokkusu** [comment]
Hey, HEY!
I don't have access to a computer so we are screwed. Abandoned ship, it's over.

... I'll try and use this hotel computer. give me like 10 minutes

**Comment by Merubokkusu** [comment]
Bunch of plebs just sitting on the chairs where the computers are, my social anxiety is too strong for me to them to Leave.

**Comment by Merubokkusu** [comment]
Tell them*

**Comment by Merubokkusu** [comment]
Actually, I cant really figure out the problem on this computer.

Whats the error?

**Comment by Technoturnovers** [comment]
insultgenerator is a DEAD WEBSITE. it is on a parked domain thingy. turrdurr

**Comment by Technoturnovers** [comment]
if you want it to work you need to use something else

**Comment by Merubokkusu** [comment]
I cant test it from this computer, let me know if it works.


_probably not_

**Comment by Technoturnovers** [comment]
lolno@urnotgettingmypcname:~/insults/discord-spam-bots$ python3 discord_insult_spam.py 

  File "discord_insult_spam.py", line 20

    print (insult_list)

    ^

IndentationError: unexpected indent

**Comment by Merubokkusu** [comment]
Try it now,  if not I'll definitely fix it today.

**Comment by Technoturnovers** [comment]
File "discord_insult_spam.py", line 20
    await client.send_message(discord.Object(id=DiscordChannel), insult_list[0] +" "+insult_list[1] +" "+ insult_list[3])
    ^
IndentationError: unexpected indent

**Comment by Technoturnovers** [comment]
sheeet it messed up the spacing

**Comment by Technoturnovers** [comment]
`
  File "discord_insult_spam.py", line 20
    await client.send_message(discord.Object(id=DiscordChannel), insult_list[0] +" "+insult_list[1] +" "+ insult_list[3])
    ^
IndentationError: unexpected indent
`

**Comment by Merubokkusu** [comment]
Well, for some reason its not fully working for me at least.
Hoping its just this computer.

Everything should be working, also changed the login from user and pass to token.

**Comment by Merubokkusu** [comment]
![fixed](https://m.popkey.co/9d262c/94bvv_s-200x150.gif)
fixed everything.
