### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kenner-G** [Merubokkusu/discord-spam-bots#10]
Make it so the users don't have to join the servers to spam text? 
I'll donate to your little tip jar if you do! :)

**Comment by Merubokkusu** [comment]
Impossible sadly, bot users can't accept invite links.

[Discord.py Docs - Accept_Invite](http://discordpy.readthedocs.io/en/latest/api.html?highlight=accept_invite#discord.Client.accept_invite)
