### ISSUE TITLE
how install

### ISSUE THREAD

**Issue by ThatRedDragon** [Merubokkusu/discord-spam-bots#110]
me stupid how install

**Comment by RedFurrFox** [comment]
Install the plugin file and drag the file on plugins of chrome or Firefox

**Comment by RedFurrFox** [comment]
Ahhh shit wrong comment. please consider my first comment here as invalid. My bad

**Comment by ThatRedDragon** [comment]
Lmao it's ok

**Comment by HalfAsleepAdam** [comment]
> Ahhh shit wrong comment. please consider my first comment here as invalid. My bad

Nah it's cool

**Comment by HalfAsleepAdam** [comment]
> Ahhh shit wrong comment. please consider my first comment here as invalid. My bad

can you still teach me how

**Comment by RedFurrFox** [comment]
> > Ahhh shit wrong comment. please consider my first comment here as invalid. My bad
> 
> can you still teach me how
>
>> https://github.com/Merubokkusu/discord-spam-bots/wiki. Sorry for the late reply
