### ISSUE TITLE
"Something went wrong (;3;)"

### ISSUE THREAD

**Issue by Kenner-G** [Merubokkusu/discord-spam-bots#13]
I am getting this error:
"Something went wrong (;3;)"
But it is still sending the message. It's getting annoying. Any fix?

**Comment by Merubokkusu** [comment]
That's just telling you someone has DMs shut off from server members.
You could customize it to say whatever you want, its on line '#49' in [discord_text_spam_dm.py](https://github.com/Merubokkusu/discord-spam-bots/blob/194a9a46cb768bdb7810e45ade6f7959ce37c390/discord_text_spam_dm.py#L49)
![Settings](https://a.safe.moe/LqjEc.png)
