### ISSUE TITLE
Multiple user spam errors

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/discord-spam-bots#13]
_**I am using Linux for this (start_linux.py)**_

Hey there! Lovely spam bot though there are a few errors with allowing multiple tokens or emails, yes I have read [this](https://github.com/Merubokkusu/discord-spam-bots/wiki/Adding-accounts) but none of these method works.

When using the tokens.txt, it only uses the top one, not the second or below that, and for the **userToken** **=** **('')** it doesn't find it, only works with 1 email and password or token.

Thanks, Shad

**Comment by Merubokkusu** [comment]
I'll get it working, might be 1-3 days as I'm having some pretty hard depression for some reason.

**Comment by ghost** [comment]
Oh, alright, gl

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/commit/f036ce836d5bd808407f83ffd68349909b64f352

Fixed.
Working on getting all of the other bots working right now.
