### ISSUE TITLE
Installiation

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/discord-spam-bots#14]
How do I install python 3.6.4 anyways? I can't find a way to do it on Linux Debian strech, if there is a link please pass it to me

**Comment by ghost** [comment]
Sorted
Users for Linux can [use this](https://www.rosehosting.com/blog/how-to-install-python-3-6-4-on-debian-9/) depending on version

**Comment by ghost** [comment]
Wrong again, messed up as pip wouldnt work

**Comment by Merubokkusu** [comment]
try "pip3"

**Comment by ghost** [comment]
pip3 is only 3.5

**Comment by Merubokkusu** [comment]
I would just uninstall python3.5 and pip and reinstall python

**Comment by ghost** [comment]
Alright

**Comment by ghost** [comment]
Nope

**Comment by Merubokkusu** [comment]
Not really sure as I only really know the basics of Linux. Anything above 3.6.4 should work though

**Comment by ghost** [comment]
Alright, thanks
