### ISSUE TITLE
How do you get user token?

### ISSUE THREAD

**Issue by PRi0NiTY** [Merubokkusu/discord-spam-bots#15]
the video on youtube in unavailable

**Comment by Merubokkusu** [comment]
1. Go to https://discordapp.com/channels/@me
2. Press Ctrl+Shift+I
3. Click application
4. Token

Theracinglion has a tutorial, I'll have to make on soon https://github.com/TheRacingLion/Discord-SelfBot/wiki/Discord-Token-Tutorial (only use it to get the token, the rest is set up for his bot)
