### ISSUE TITLE
spam picture

### ISSUE THREAD

**Issue by sadoj-kuro** [Merubokkusu/discord-spam-bots#16]
spam picture not working or I do not know how to use it
in config file

`#Picture spam
DirPictures = 'home\\bot\\discord-spam-bots\\pictures\\' # Picture(s) location !ALWAYS DOUBLE SLASH AND END WITH THAT DOUBLE SLASH YO!
`

Select a bot: 2
Started Image Spam
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bots/server/discord_image_spam.py", line 25, in on_ready
    UpImage = random.choice(os.listdir(DirPictures))
FileNotFoundError: [Errno 2] No such file or directory: 'home\\\bot\\\discord-spam-bots\\\pictures\\\

**Comment by ghost** [comment]
Looks like you're using linux.

The linux_start.py was only released a few days ago and he stated that auto-join does not work (which I think he fixed) and also said picture spam will not work currently, will be fixed soon

> [6e14cc1](https://github.com/Merubokkusu/discord-spam-bots/commit/6e14cc1c9af79ed4deb6eba3d3afc6c726cb697b)
> 
> All of the spammers currently work but the image spammer and auto server joining, I'll add them within a day.
> 
> Make sure your pythonCommand is set to whatever you use to call the python command
> [a52c0be](https://github.com/Merubokkusu/discord-spam-bots/commit/a52c0bef3adfc2da344769a36243700d7fd1dfa8)

**Comment by Merubokkusu** [comment]
`//home//<username here>//Desktop//discord-spam-bots-master//pics//`
I have mine set like this and it works.

So try this
`//home//bot//discord-spam-bots//pictures//`

**Comment by sadoj-kuro** [comment]
its working for you but not in linux ?

i have tested with // before not working

**Comment by Merubokkusu** [comment]
Try putting the // in the beginning of the directory, the bot can't find the path

**Comment by sadoj-kuro** [comment]
i have say i have testing with // before directory and not working but im on linux so its not really fix

> 6e14cc1

All of the spammers currently work but the image spammer and auto server joining, I'll add them within a day.

Make sure your pythonCommand is set to whatever you use to call the python command
a52c0be

**Comment by Merubokkusu** [comment]
What linux distro are you running?
I used Ubuntu to test it.

**Comment by sadoj-kuro** [comment]
debian 8

**Comment by Merubokkusu** [comment]
Can you screenshot your terminal after running the command
