### ISSUE TITLE
Syntax was invalid

### ISSUE THREAD

**Issue by SoftWheat89** [Merubokkusu/discord-spam-bots#16]
https://gyazo.com/4f99562ef36d2ec60f8f35b8bf79097c

and

https://gyazo.com/4f99562ef36d2ec60f8f35b8bf79097c﻿

**Comment by Merubokkusu** [comment]
Did you install the requirements?

**Comment by SoftWheat89** [comment]
Yeah first Python wasnt working on my command prompt I fixed that now Idk about this,

**Comment by Merubokkusu** [comment]
So you install discord.py and bs4?

**Comment by SoftWheat89** [comment]
Hmm idk maybe not can you give me the link please?

**Comment by Merubokkusu** [comment]
Alright.
Open up cmd and write "pip install discord.py" after that installs write "pip install bs4"

**Comment by SoftWheat89** [comment]
In command prompt?

**Comment by Merubokkusu** [comment]
Yep

**Comment by SoftWheat89** [comment]
Its saying pip is not recognized  as a internal  or external command.

**Comment by Merubokkusu** [comment]
Get the python installer and open it 

![image](https://user-images.githubusercontent.com/14025511/33157870-65083454-cfd3-11e7-8bb5-914431fa0189.png)
![image](https://user-images.githubusercontent.com/14025511/33157879-75a84484-cfd3-11e7-8722-e8bd59e202ff.png)
![image](https://user-images.githubusercontent.com/14025511/33157896-a2b877aa-cfd3-11e7-8a59-ba823236df1a.png)

**Comment by SoftWheat89** [comment]
I dont have that I have Python  3.0.1

**Comment by Merubokkusu** [comment]
Oh, this was made for python 3.6

**Comment by SoftWheat89** [comment]
Oh im sorry can you give me the link?

**Comment by Merubokkusu** [comment]
https://www.python.org/downloads/release/python-360/ no problem

**Comment by SoftWheat89** [comment]
Which PEP should I download?

**Comment by Merubokkusu** [comment]
Scroll down to files

**Comment by SoftWheat89** [comment]
Ok I got  

Windows x86 embeddable zip file | Windows |   | 1adf2fb735c5000af32d42c39136727c | 6315855 | SIG
-- | -- | -- | -- | -- | --

**Comment by SoftWheat89** [comment]
That's the one I got its installing.

**Comment by SoftWheat89** [comment]
It's installed.

**Comment by Merubokkusu** [comment]
um, I've actually never installed it that way.
I usually use the installer but if that works then good.

**Comment by SoftWheat89** [comment]
Ok now what?

**Comment by SoftWheat89** [comment]
Their I clicked modify pip was checked did it....Now its finished.

**Comment by Merubokkusu** [comment]
Now you can install the stuff with pip

**Comment by SoftWheat89** [comment]
What do I type?

**Comment by Merubokkusu** [comment]
pip install discord.py
pip install bs4

**Comment by SoftWheat89** [comment]
'pip' is not recognized as an internal or external command,
operable program or batch file.

Im getting that.

**Comment by Merubokkusu** [comment]
Did you check everything like this
https://github.com/Merubokkusu/discord-spam-bots/issues/16#issuecomment-346524694

**Comment by SoftWheat89** [comment]
Oop's forgot to check one thing sorry.

**Comment by SoftWheat89** [comment]
Thank's ok now I type it.

**Comment by Merubokkusu** [comment]
Yep

**Comment by SoftWheat89** [comment]
It's downloading discord.api

**Comment by SoftWheat89** [comment]
It got downloaded now  pip install discord.py

**Comment by SoftWheat89** [comment]
Ok done.

**Comment by SoftWheat89** [comment]
:)

**Comment by Merubokkusu** [comment]
Did you also install bs4?
pip install bs4

**Comment by SoftWheat89** [comment]
Yeah both :)

**Comment by SoftWheat89** [comment]
It didnt say successful in bs4 something with Hold on gonna do it again to make sure

**Comment by SoftWheat89** [comment]
Ok now it said successful.

**Comment by Merubokkusu** [comment]
Alright, the bot should work.
The config is edited I assume?

**Comment by SoftWheat89** [comment]
Yeah
I put 1 token in it.

**Comment by SoftWheat89** [comment]
So I go to a discord then load it
then boom

**Comment by SoftWheat89** [comment]
??

**Comment by Merubokkusu** [comment]
Yeah the channel ID is also set?

**Comment by SoftWheat89** [comment]
How do I get that?

**Comment by SoftWheat89** [comment]
Oh the discord id

**Comment by SoftWheat89** [comment]
The invite right?

**Comment by Merubokkusu** [comment]
![image](https://user-images.githubusercontent.com/14025511/33158380-7db23d34-cfd7-11e7-8152-56bc2a48d681.png)

**Comment by SoftWheat89** [comment]
Ok I put my channel id.

**Comment by SoftWheat89** [comment]
Now do I start?

**Comment by Merubokkusu** [comment]
Yep

**Comment by SoftWheat89** [comment]
Ok

**Comment by Merubokkusu** [comment]
Let me know if it works.

**Comment by SoftWheat89** [comment]
It didnt work nothing happened.

**Comment by Merubokkusu** [comment]
:thinking: It could be using the older python, the 3.1 one

**Comment by SoftWheat89** [comment]
Hmm maybe
Can you send me the link

**Comment by SoftWheat89** [comment]
It loaded then wrote random stuff then exited

**Comment by Merubokkusu** [comment]
I mean, since you have two different pythons installed it could be using the older one.

**Comment by SoftWheat89** [comment]
So which one should I uninstall?

**Comment by SoftWheat89** [comment]
I have Python 3.0.1, Python Launcher, and Python 3.6.0

**Comment by SoftWheat89** [comment]
Installed.

**Comment by Merubokkusu** [comment]
Python 3.0.1 uninstall that

**Comment by SoftWheat89** [comment]
Ok I uninstalled it.

**Comment by Merubokkusu** [comment]
Alright, try it now

**Comment by SoftWheat89** [comment]
Ok

**Comment by SoftWheat89** [comment]
Dude look at this  https://gyazo.com/175fb9a0b34cf301370a40f96ea1b665

**Comment by Merubokkusu** [comment]
Open open up the python 3.6 installer and do the checks I did in
https://github.com/Merubokkusu/discord-spam-bots/issues/16#issuecomment-346524694

**Comment by SoftWheat89** [comment]
Did it.

**Comment by Merubokkusu** [comment]
Try now

**Comment by SoftWheat89** [comment]
Ok

**Comment by SoftWheat89** [comment]
Still wont let me open it.

**Comment by Merubokkusu** [comment]
Alright, uninstall everything python.
Then install this https://www.python.org/ftp/python/3.6.0/python-3.6.0.exe
Once you open it, click the "add python to PATH" then "Custom Installation"
And it should show the same stuff as  https://github.com/Merubokkusu/discord-spam-bots/issues/16#issuecomment-346524694

**Comment by SoftWheat89** [comment]
Uninstall every python

**Comment by SoftWheat89** [comment]
?

**Comment by Merubokkusu** [comment]
Yeah

**Comment by SoftWheat89** [comment]
Ok

**Comment by Merubokkusu** [comment]
Let me know when you did everything

**Comment by SoftWheat89** [comment]
Ok I uninstalled everything and installed the one you sent me.

**Comment by Merubokkusu** [comment]
Alright try to run it

**Comment by SoftWheat89** [comment]
Python is not recognized as a command

**Comment by Merubokkusu** [comment]
You probably didn't check the first thing on the installer "Add python to PATH"

**Comment by SoftWheat89** [comment]
I did now its something else

**Comment by SoftWheat89** [comment]
it's showing me this

https://gyazo.com/0d788a89f0aff433dd681760288e9322

**Comment by Merubokkusu** [comment]
Install discord.py and bs4 again

**Comment by SoftWheat89** [comment]
Ok.

**Comment by SoftWheat89** [comment]
Installed should I run it?

**Comment by Merubokkusu** [comment]
Yep

**Comment by SoftWheat89** [comment]
It didn't work it  started to load with random stuff then closed command prompt.

**Comment by Merubokkusu** [comment]
Bs4 and discord.py is installed?

**Comment by SoftWheat89** [comment]
Yeah.

**Comment by SoftWheat89** [comment]
You their?

**Comment by Merubokkusu** [comment]
I'm not really sure why its doing that, it should have been working.

**Comment by SoftWheat89** [comment]
Yeah

**Comment by SoftWheat89** [comment]
Thx though.

**Comment by Merubokkusu** [comment]
Try to see if you can see what it says before it closes

**Comment by SoftWheat89** [comment]
https://gyazo.com/0d788a89f0aff433dd681760288e9322 

It says this.

**Comment by Merubokkusu** [comment]
Restart your computer, pretty much what that means is that discord.py isn't installed

**Comment by SoftWheat89** [comment]
I restarted my computer its showing me explorer .exe

**Comment by Merubokkusu** [comment]
I don't understand what you mean.

**Comment by SoftWheat89** [comment]
Oh sorry ok should I run it?

**Comment by Merubokkusu** [comment]
Type "python --version" into the command prompt, let me know what it returns.

**Comment by SoftWheat89** [comment]
It said Python 3.6.0

**Comment by Merubokkusu** [comment]
Alright, good. Now try running the bot

**Comment by SoftWheat89** [comment]
Ok

**Comment by SoftWheat89** [comment]
It got loaded with random text and closed im gonna try to screenshot it.

**Comment by SoftWheat89** [comment]
I got it here

https://gyazo.com/65efed6073aec51865f84fb28836cd0c

**Comment by SoftWheat89** [comment]
![screenshot 139](https://user-images.githubusercontent.com/33918274/33186305-20671d76-d04e-11e7-9be2-2ecb24f1814d.png)

**Comment by Merubokkusu** [comment]
That mean's your user token is wrong.
It should look like this in the config
![image](https://a.safe.moe/RndNq.png)

**Comment by SoftWheat89** [comment]
![screenshot 141](https://user-images.githubusercontent.com/33918274/33186397-e45a8a38-d04e-11e7-8096-4895e89a6159.png)

**Comment by SoftWheat89** [comment]
I have a lot of tokens.

**Comment by SoftWheat89** [comment]
I only put one.

**Comment by Merubokkusu** [comment]
![image](https://a.safe.moe/UWB7Y.png)
User token goes in between [''] to add more make it like ['token','token']
Channel ID goes in between ''

Removing that post because people can steal your account with the token.

**Comment by SoftWheat89** [comment]
Oh ok.

**Comment by SoftWheat89** [comment]
![screenshot 142](https://user-images.githubusercontent.com/33918274/33186489-9720bb06-d04f-11e7-88a3-1b9733617adc.png)

**Comment by SoftWheat89** [comment]
Im confused.

**Comment by Merubokkusu** [comment]
![image](https://a.safe.moe/AsaJW.png)

**Comment by Merubokkusu** [comment]
That goes in there

**Comment by SoftWheat89** [comment]
![image](https://user-images.githubusercontent.com/33918274/33186606-47525462-d050-11e7-83a6-82eca7e5fc24.png)

**Comment by SoftWheat89** [comment]
Their.

**Comment by Merubokkusu** [comment]
Yeah that's correct, just remove the last empty space in the DiscordChannel

**Comment by SoftWheat89** [comment]
The comma

**Comment by SoftWheat89** [comment]
oh the last straight line that's small.

**Comment by SoftWheat89** [comment]
Is that it?

**Comment by Merubokkusu** [comment]
![image](https://a.safe.moe/fEKPK.png)
You have an empty space after the 6

**Comment by SoftWheat89** [comment]
Their now its together the line after 6.

**Comment by SoftWheat89** [comment]
Sorry for the trouble.

**Comment by Merubokkusu** [comment]
No problem, you can run it now.

**Comment by SoftWheat89** [comment]
It did the same thing again.

**Comment by SoftWheat89** [comment]
![screenshot 144](https://user-images.githubusercontent.com/33918274/33186679-eb3a9e0e-d050-11e7-84fa-aaed3309510a.png)

**Comment by SoftWheat89** [comment]
Anything wrong here?

**Comment by Merubokkusu** [comment]
It should be working.

**Comment by SoftWheat89** [comment]
Hmm that's weird.

**Comment by SoftWheat89** [comment]
It loads command prompt with random words like a lot then it closes.

**Comment by Merubokkusu** [comment]
Same as https://github.com/Merubokkusu/discord-spam-bots/issues/16#issuecomment-346683374 ?

**Comment by SoftWheat89** [comment]
Yeah.

**Comment by Merubokkusu** [comment]
You are getting the token from using ctrl+shift+I on the discord website?

**Comment by SoftWheat89** [comment]
Yeah

**Comment by SoftWheat89** [comment]
I got it from application local discord.app.com then Token.

**Comment by SoftWheat89** [comment]
Yeah
Why?

**Comment by SoftWheat89** [comment]
I just close it

**Comment by SoftWheat89** [comment]
It saves .

**Comment by Merubokkusu** [comment]
Open the file back up, hit ctrl+s

**Comment by Merubokkusu** [comment]
![image](https://a.safe.moe/d15C6.png)
If that is red it means it hasn't been saved.

**Comment by SoftWheat89** [comment]
Its not red.

**Comment by SoftWheat89** [comment]
The one I got tokens from is red.

**Comment by Merubokkusu** [comment]
I really don't know then, makes sure you are editing the right config in the correct folder.

**Comment by SoftWheat89** [comment]
![screenshot 145](https://user-images.githubusercontent.com/33918274/33186902-19fcda48-d053-11e7-969c-772114cd1b29.png)

**Comment by SoftWheat89** [comment]
I put my configs here

**Comment by Merubokkusu** [comment]
That doesn't go with my bot.
I'm not sure what it is.

**Comment by SoftWheat89** [comment]
It's another bot I have it doesnt work so im using my configs on this one.

**Comment by Merubokkusu** [comment]
Oh, well you have to use my config.py.
That one wont work with it.

**Comment by SoftWheat89** [comment]
Oh im sorry

**Comment by SoftWheat89** [comment]
Can I have a token I can use im really confused.

**Comment by Merubokkusu** [comment]
I really can't explain anymore and I can't give you a token.

You can get a token from making a discord account and pressing ctrl+shift+i

![image](https://a.safe.moe/hMZtV.png) The config.py has to be filled out like this.

**Comment by SoftWheat89** [comment]
Ok hold on thx.

**Comment by SoftWheat89** [comment]
I got a token

**Comment by SoftWheat89** [comment]
![screenshot 146](https://user-images.githubusercontent.com/33918274/33187195-b0de76fe-d055-11e7-853e-0d2a2823fe6c.png)

**Comment by Merubokkusu** [comment]
Yes that's correct, now save it.

**Comment by SoftWheat89** [comment]
it's red I forgot to save it
do I click save.

**Comment by Merubokkusu** [comment]
Yes

**Comment by SoftWheat89** [comment]
Did it should I run it?

**Comment by SoftWheat89** [comment]
Sorry for making this hard.

**Comment by SoftWheat89** [comment]
Or take too long.

**Comment by Merubokkusu** [comment]
Yes run it.

**Comment by SoftWheat89** [comment]
It still didnt work :(

**Comment by SoftWheat89** [comment]
Wait
Here

**Comment by SoftWheat89** [comment]
![screenshot 147](https://user-images.githubusercontent.com/33918274/33187385-fe074694-d056-11e7-9ee6-9544954d3fa3.png)

**Comment by SoftWheat89** [comment]
I saved it

**Comment by Merubokkusu** [comment]
Yeah that's all correct, make sure you are running the right start.py

**Comment by SoftWheat89** [comment]
![screenshot 148](https://user-images.githubusercontent.com/33918274/33187448-5b4b9a26-d057-11e7-96aa-70ac59376b69.png)

**Comment by Merubokkusu** [comment]
:thinking: I have no clue. It should have worked.

**Comment by SoftWheat89** [comment]
How come it works for the guy who posted it on youtube he clicked on run then powershell then he used it.

**Comment by Merubokkusu** [comment]
I don't know, you're doing something wrong with it.
What does it say now once you run it?

**Comment by SoftWheat89** [comment]
It shows a full whole text then closes  https://user-images.githubusercontent.com/33918274/33186305-20671d76-d04e-11e7-9be2-2ecb24f1814d.png

**Comment by SoftWheat89** [comment]
Im sorry if your getting mad.

**Comment by Merubokkusu** [comment]
Is the bot in the server?
You have to join it yourself.

**Comment by SoftWheat89** [comment]
No

**Comment by SoftWheat89** [comment]
Maybe its that

**Comment by SoftWheat89** [comment]
:O

**Comment by SoftWheat89** [comment]
I joined the server

**Comment by SoftWheat89** [comment]
but I dont have a bot.

**Comment by Merubokkusu** [comment]
The account with the token you have has to be in the server.

**Comment by SoftWheat89** [comment]
Oh its not

**Comment by SoftWheat89** [comment]
How do I add it?

**Comment by SoftWheat89** [comment]
Oh
Hodl on

**Comment by SoftWheat89** [comment]
Hold

**Comment by SoftWheat89** [comment]
It wont work im on my bots account I click run it does the samething its on the server.

**Comment by Merubokkusu** [comment]
The account joined the server?

**Comment by SoftWheat89** [comment]
Yeah'
I was on my bot account my alt account on the server

**Comment by SoftWheat89** [comment]
Dude

**Comment by Merubokkusu** [comment]
I really don't know.

**Comment by SoftWheat89** [comment]
Ok im gonna use my main account I put my token it's in the server now what do I do?

**Comment by SoftWheat89** [comment]
I have a great way to fix it I give my config or the file to you and you check it.

**Comment by SoftWheat89** [comment]
So you get a clear idea of what's going on.

**Comment by Merubokkusu** [comment]
Add me on discord. Merubokkusu#3168

**Comment by SoftWheat89** [comment]
Ok
