### ISSUE TITLE
Not doing anything after logging in

### ISSUE THREAD

**Issue by Xiyangyang1026** [Merubokkusu/discord-spam-bots#17]
I select a bot and wait. I used multiple accounts.
![image](https://user-images.githubusercontent.com/32981461/52680392-3b237700-2f06-11e9-8523-1bb03485fbb4.png)

**Comment by Merubokkusu** [comment]
Is the bot in the server?

**Comment by Xiyangyang1026** [comment]
Yes

**Comment by Merubokkusu** [comment]
Check if your firewall is blocking python from connecting to the internet
Also if you can provide your config and remove any sensitive information from your config (invite link, tokens etc)

**Comment by Xiyangyang1026** [comment]
![image](https://user-images.githubusercontent.com/32981461/52684828-95780400-2f15-11e9-9ef9-d0e26a147fa1.png)
It isn't blocking python. I've run other python bots off my laptop.

**Comment by Merubokkusu** [comment]
All of the requirements are installed also?

**Comment by Xiyangyang1026** [comment]
yes

**Comment by Merubokkusu** [comment]
try creating a file called tokens.txt in the root of the folder and put your tokens there in this format
```
token
token
token
```

**Comment by Xiyangyang1026** [comment]
That didn't work either, still stuck here
![image](https://user-images.githubusercontent.com/32981461/52685159-bc830580-2f16-11e9-8ea7-b31bb0cb4fea.png)

**Comment by Merubokkusu** [comment]
I'm actually not sure, any more info you can provide?
