### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by foihfh3oh3f** [Merubokkusu/discord-spam-bots#2]
Yo I got no idea how to use this, can you make a tutorial or explain? Also is this one of the spambots that uses multiple bots in the discord to spam instead of just your user, because that is the type of spambot I am looking for.

**Comment by Technoturnovers** [comment]
edi the config.py to get the settings you need, put images in the specified image folder if you are using image spam, and run the script. it only supports 1 user tho

**Comment by Merubokkusu** [comment]
I could probably make it support multiple accounts, but you would have to make the accounts etc.

**Comment by Merubokkusu** [comment]
Try using multiple accounts, it may work now.
