### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by AceFN** [Merubokkusu/discord-spam-bots#20]
I honestly have no clue what this error means
![image](https://user-images.githubusercontent.com/47253541/54549779-abf4fd80-49a2-11e9-9cb5-3a1c647ff92c.png)

**Comment by Merubokkusu** [comment]
Fixed, download the latest version.
https://github.com/Merubokkusu/discord-spam-bots/commit/504c412100cb771500cb7545bc5062f2d3748f21
