### ISSUE TITLE
Another request:

### ISSUE THREAD

**Issue by PRi0NiTY** [Merubokkusu/discord-spam-bots#20]
Again, this is not to bother you but, could you add another feature, so that it selects a random server that the user is in?

**Comment by Merubokkusu** [comment]
So you want it to select a random server that the bot is in to spam?

**Comment by PRi0NiTY** [comment]
Also, could you stabilize it a bit more, like make a command gui where it says how many tokens worked, or how many msgs that have been spammed example: [Spammed:(ammount) Working Tokens:()]

**Comment by Merubokkusu** [comment]
The challenge with that is that each token is launched with a new instance of python, I'm not totally sure if I'd be able to grab each amount.

**Comment by PRi0NiTY** [comment]
oh okay
