### ISSUE TITLE
Says "Started Text Spam" but not spamming?

### ISSUE THREAD

**Issue by AceFN** [Merubokkusu/discord-spam-bots#21]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Python Version [e.g. 3.6.4]

**Additional context**

**Comment by Merubokkusu** [comment]
Os and python version?

**Comment by AceFN** [comment]
python 3.6.8 and i don't know Os i i'm honest lol

**Comment by Merubokkusu** [comment]
Operating system, like windows, Linux etc.
And this works with 3.6.4 I'm not sure about it working with anything 3.6.6
and above

**Comment by Merubokkusu** [comment]
**inactive**
