### ISSUE TITLE
Started spam

### ISSUE THREAD

**Issue by alyy** [Merubokkusu/discord-spam-bots#26]
It says started spam and doesnt spam.
Python 3.7.2
Mac OSX

**Comment by Merubokkusu** [comment]
This isn't tested on 3.7+ so i'm unsure if it works

This is made using 3.6.4

**Comment by alyy** [comment]
Created an environment with 3.6.4 still doesn't spam

**Comment by Merubokkusu** [comment]
Hmm, try this. just want to make sure its not something that was changed
https://raw.githubusercontent.com/Merubokkusu/discord-spam-bots/aa83843576d1a3cc2c97d282d684b1ec780c2861/start_linux.py

**Comment by alyy** [comment]
Same problem, says started text spam but doing nothing

**Comment by Merubokkusu** [comment]
Can I see the terminal log?

**Comment by alyy** [comment]
It doesnt error anything
