### ISSUE TITLE
Help With a lot 

### ISSUE THREAD

**Issue by Dainte** [Merubokkusu/discord-spam-bots#29]
Theres a lot of issues add me Vex#7069 please

**Comment by enemy1337** [comment]
Same here, please help me out on discord if possible or just respond to my issue. 
Discord: enemy#4080

**Comment by Merubokkusu** [comment]
I don’t talk through discord.
What are your issues?

**Comment by Dainte** [comment]
I get a p.wait() error on start.py

**Comment by Dainte** [comment]
Traceback (most recent call last):
  File "C:/Users/jonab/PycharmProjects/DiscordBot/discord-spam-bots-master/start.py", line 134, in <module>
    p.wait()
NameError: name 'p' is not defined****
