### ISSUE TITLE
Issue whilst running

### ISSUE THREAD

**Issue by iPredictable** [Merubokkusu/discord-spam-bots#3]
Terminal Logs
Write spam text : 3
python discord_text_spam.py '3'
Traceback (most recent call last):
  File "start.py", line 36, in <module>
    p = subprocess.Popen('python discord_text_spam.py ' + token + " "+'"'+spam_text+'"')
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'python discord_text_spam.py *USERTOKEN* "3"'

**Comment by iPredictable** [comment]
BTW running on OS X

**Comment by Merubokkusu** [comment]
Weird,  I'll try it when I get home.
Also you left your usertoken in the log before 😬 I edited it and removed it for you.

**Comment by Merubokkusu** [comment]
Oh, is it only the text spammer or all of them?

**Comment by iPredictable** [comment]
I haven't tried others, but tbh just wanted the text spam, also thanks lol

**Comment by Merubokkusu** [comment]
Alright, I updated the 'start.py' code. Let me know if it fixed it

**Comment by iPredictable** [comment]
Still doesn't work, Im also a beginner with python and I tried messing with the input, couldn't fix it.

 File "/Users/Kasra/Desktop/discord-spam-bots-master/start.py", line 34, in <module>
    spam_text = (input("Write spam text : "))
  File "<string>", line 1, in <module>
NameError: name 'test' is not defined

**Comment by Merubokkusu** [comment]
Alright replace line #37 with
```python
        p = subprocess.Popen(['python','discord_text_spam.py',token,spam_text],shell=True)
```
let me if that works.
