### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by enemy1337** [Merubokkusu/discord-spam-bots#30]
EDIT YOUR CONFIG.PY BEFORE USING!
Type one of the following numbers to launch that spammmer
       +========-Server Spammers-=========+
1 : Text Spammer - Write your own text to spam
2 : Image Spammer - Spam random images in a selected folder
3 : Insult Spammer - Picks insults online and spams them
         +========-DM Spammers-=========+
4 : Text Spammer - Write your own text to spam
5 : Image Spammer - Spam random images in a selected folder
6 : Insult Spammer - Picks insults online and spams them
           +========-Other-=========+
7 : Join Server - Join the server thats written in the config
           +========-Account Creator-=========+
8 : Account creator - Create bulk accounts
9 : Account verifier - Verify accounts
Select a bot: 8
solving ref captcha...
Traceback (most recent call last):
  File "C:\Users\rived\Desktop\discord-spam-bots-master\start.py", line 149, in <module>
    p = subprocess.Popen([pythonCommand,'bots/misc/account-creator/account_creator.py',enp[0],enp[1],proxy_list[proxy_number]])
IndexError: list index out of range

**Comment by enemy1337** [comment]
Please help me out i need this asap . @Merubokkusu

**Comment by Merubokkusu** [comment]
How’s your proxy list formatted?

**Comment by enemy1337** [comment]
I tried ip:port then ip|port and now I was just using 1 line of an IP no port

**Comment by enemy1337** [comment]
So in this instance the proxies.txt file was just like

127.0.0.1

but with an actual proxy

**Comment by enemy1337** [comment]
looks like I fixed it by using ip:port, it made like 1 account using 26 captchas from 2captcha but it didnt save the token to a file
