### ISSUE TITLE
Error when i try Account Creator.

### ISSUE THREAD

**Issue by userunix1** [Merubokkusu/discord-spam-bots#31]
edit*

**Comment by Merubokkusu** [comment]
This isn’t tested with python 3.7

Only with 3.6.4

**Comment by userunix1** [comment]
edit*

**Comment by userunix1** [comment]
Still waiting for an answer.

Thanks

**Comment by Merubokkusu** [comment]
Type ‘python -v’ and send me the output and send me how your proxy list is formatted

**Comment by userunix1** [comment]
edit*

**Comment by userunix1** [comment]
Do you have any good news?
