### ISSUE TITLE
Discord account gets banned on creation

### ISSUE THREAD

**Issue by encloinc** [Merubokkusu/discord-spam-bots#33]
As soon as the account is created and I login to it gives me the something suspicious is going on error

**Comment by Merubokkusu** [comment]
Are you verifying the accounts, using proxies and how are you logging in with the accounts?

**Comment by encloinc** [comment]
thorugh incognito mode and using the same ip I used to create them. I dont need them to be verified

**Comment by Merubokkusu** [comment]
Yeah, you shouldn’t login to them like that. They’re mainly for like one shot things.
>create
>use ASAP
>delete

**Comment by encloinc** [comment]
I tried using their token though as soon as it was created and it also gave me the error
