### ISSUE TITLE
Port the script to mac

### ISSUE THREAD

**Issue by Rainbeep** [Merubokkusu/discord-spam-bots#34]
As a macOS user I want to ask if the script will be macOS friendly in future

**Comment by Rainbeep** [comment]
Additionally, I get this error when I try to run the script:
`Select a bot: 1
  File "bots/server/discord_text_spam.py", line 33
    async def on_ready():
        ^
SyntaxError: invalid syntax`

**Comment by Merubokkusu** [comment]
The script is fully universal on all OS.
windows, mac and linux

and what is your python version.

**Comment by Rainbeep** [comment]
Python 2.7.15 and I'm running it in the terminal window.
It's also possible that I just don't know how to use the script properly, but it appears that I configured everything that is necessary for it to run.

**Comment by Rainbeep** [comment]
I tried running the script on fresh with everything configured again.
This error appears:
![unknown](https://user-images.githubusercontent.com/45702548/61809688-01b54700-ae68-11e9-84d8-34e622c98ab3.png)

**Comment by Merubokkusu** [comment]
That would be the problem, this script is made for python 3.6.4

**Comment by Rainbeep** [comment]
Oh alright, I'll try that out.
