### ISSUE TITLE
SyntaxError:

### ISSUE THREAD

**Issue by HideakiAtsuyo** [Merubokkusu/discord-spam-bots#38]
Select a bot: 8
Traceback (most recent call last):
  File "bots/misc/account-creator/account_creator.py", line 18, in <module>
    from config import *
  File "./././config.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file ./././config.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Traceback (most recent call last):
  File "start.py", line 149, in <module>
    p = subprocess.Popen([pythonCommand,'bots/misc/account-creator/account_creator.py',enp[0],enp[1],proxy_list[proxy_number]])
IndexError: list index out of range

**Comment by acryllect** [comment]
Same issue here

**Comment by Merubokkusu** [comment]
Python version

**Comment by acryllect** [comment]
Just realized I ran it using "python" (which starts python 2.7.x) instead of "python3" (my main installation of python, version 3.7.3)

**Comment by Merubokkusu** [comment]
Should also edit the python command in the config, I’m not sure if it works
on 3.7

**Comment by acryllect** [comment]
I am having another issue, not the one mentioned, could it be possible to contact you privately as to not ruin the thread?

**Comment by HideakiAtsuyo** [comment]
Okay thank you :)
