### ISSUE TITLE
SyntaxError - Line 33 of discord_text_spam.py

### ISSUE THREAD

**Issue by acryllect** [Merubokkusu/discord-spam-bots#39]
Ran `python3 start.py`
`Select a bot: 1` 
`Write spam text : Test`
  `File "bots/server/discord_text_spam.py", line 33
    async def on_ready():
        ^
SyntaxError: invalid syntax`

What's up with this? Checked out the file, looks like nothing's wrong.

**Comment by Merubokkusu** [comment]
check the pythonCommand in the config
