### ISSUE TITLE
Can I add a few...

### ISSUE THREAD

**Issue by thule2k** [Merubokkusu/discord-spam-bots#4]

**Comment by andy1337** [comment]
But works fine with text.txt, theres another question. How to read while text to spam from .txt not random line. Thanks!

**Comment by andy1337** [comment]
Looks like error occurs when you use one more lines

**Comment by thule2k** [comment]
Ex.
DiscordChannel = 'ID', 'ID'
inviteLink = 'https://discord.gg/XXXX', 'https://discord.gg/XXXX'
?

**Comment by Merubokkusu** [comment]
I could try to work on it.
As of now you cant
