### ISSUE TITLE
Getting rate limited even when using proxies

### ISSUE THREAD

**Issue by JABirchall** [Merubokkusu/discord-spam-bots#45]
**Describe the bug**
Creating discord account is get rate limited when usung proxies

![https://i.imgur.com/8UgQln4.png](https://i.imgur.com/8UgQln4.png)

ive had to remove the subprocesses, add feature to sleep the remaining rate limit time and retry creating the account after.

**Comment by Merubokkusu** [comment]
Are these free proxies?
most free proxies get rate limited.
