### ISSUE TITLE
Account creation and verification issues

### ISSUE THREAD

**Issue by erickfung** [Merubokkusu/discord-spam-bots#49]
Hi 

Thanks for the tools. I've encountered issues using the account creator and account verifier.

I used the account creator to generate multiple discord accounts via DC proxies and 2captcha in one go. I tried to verify the accounts using Account Verifier but showed error:
![image](https://user-images.githubusercontent.com/36249313/81806276-215f4e00-9514-11ea-927e-2c0e292fffee.png)

I tried to verify the accounts one by one using the verification links received from Discord, however, Discord asks me to do the SMS verification as unusual activity has been detected.

Any solutions?

Many thanks,

Erik

**Comment by Merubokkusu** [comment]
Its either the proxy was banned or for some reason the proxy isnt being loaded, I'll try to figure it out soon.
