### ISSUE TITLE
After log in and choosing a bot don't work anymore

### ISSUE THREAD

**Issue by DarkDoccieDutch** [Merubokkusu/discord-spam-bots#5]
Hello, first of all thanks for sharing this awesum code!

But it's not working for me, i have tryed all bots but all gave me error.  i have a ss where i used the DM bot number 4. Hope you could help me :)

Regards,

Doccie

![image](https://user-images.githubusercontent.com/41516972/44741077-60f5c480-aafc-11e8-9521-b3e9c5445bc6.png)

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/issues/6#issuecomment-417193816

Should work now.
