### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/discord-spam-bots#50]
**Describe the bug**
On all of the features apart from the proxy checker, I get the error "list index out of range"

**To Reproduce**
Run any of the .bat files (excluding the proxy checker) and you will get an error related to "list index out of range". 
In the register .bat it just shows "list index out of range" on a lot of the attempts.
On the token grabber .bat it shows 
  File "python/discord_grabtokens.py", line 160, in <module>
    main()
File "python/discord_grabtokens.py", line 142, in main
    password = _.split(':')[2]
IndexError: list index out of range

On the verify .bat it shows
  File "python/discord_verify.py", line 231, in <module>
    main()  
File "python/discord_verify.py", line 197, in main
    email = _.split(':')[3]
IndexError: list index out of range

Simillar errors occur on the rest.

**Expected behavior**
I expected it to work.

**Screenshots**
When running the register .bat:
![image](https://user-images.githubusercontent.com/65553427/82228984-bfdb1d00-9921-11ea-8d25-293d192a7c76.png)

token grabber .bat :
![image](https://user-images.githubusercontent.com/65553427/82229084-e0a37280-9921-11ea-964c-594ca19bb3ac.png)

verify .bat:
![image](https://user-images.githubusercontent.com/65553427/82229140-f31dac00-9921-11ea-9917-fc35e0e86282.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.8.2

**Additional context**

**Comment by Merubokkusu** [comment]
What script is this?
I don't have any .bats or anything called discord_grabtokens.py

**Comment by ghost** [comment]
sorry this is for a different bot. I must have gotten them mixed up
