### ISSUE TITLE
Can't use text spam

### ISSUE THREAD

**Issue by Georglider** [Merubokkusu/discord-spam-bots#55]
**Describe the bug**
Can't use text spam

**Expected behavior**
I wanted my account to spam for testing a spam bot, but spam bot wasn't working

**Screenshots**
https://imgur.com/a/nS3ekIH

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Python Version [3.8.2]

**Additional context**
Any other spam also doesn't work

**Comment by Merubokkusu** [comment]
First, you're using 3.8 when this needs 3.6.4
Second, No discord selfbots work at the moment.
