### ISSUE TITLE
join issue

### ISSUE THREAD

**Issue by ManagerLeet** [Merubokkusu/discord-spam-bots#6]
hello
bot working nice but not join server automatically. it gives this error:
![ss](https://user-images.githubusercontent.com/42797297/44770127-a69fa500-ab6f-11e8-9c76-a7d4ee5983c7.jpg)
please help
thanks

**Comment by ManagerLeet** [comment]
and this error:
![image](https://user-images.githubusercontent.com/42797297/44770613-414cb380-ab71-11e8-92bd-1a4aad757b64.png)

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/commit/131b65153b31464824668ea90fa3b00d1e43ba6f

Updated the script.

Download the newest version and try again, config does not need to be overwritten.
