### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Jeremy2131** [Merubokkusu/discord-spam-bots#7]
I got this error when i try start bots from my dedicated server.. whats wrong?
![1](https://user-images.githubusercontent.com/20999549/30772101-ad400260-a05d-11e7-8fb6-3f2cd078fcf0.png)

**Comment by Merubokkusu** [comment]
Try running "pip install --upgrade --force-reinstall discord.py"

**Comment by Jeremy2131** [comment]
@Merubokkusu where i can find it

**Comment by Jeremy2131** [comment]
@Merubokkusu work,ty
