### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by DarkDoccieDutch** [Merubokkusu/discord-spam-bots#7]
I have downloaded the updated version, but it still don't work completly for me. 

This error i got when i use bot nr. 1
![image](https://user-images.githubusercontent.com/41516972/44839390-f26d4f80-ac3e-11e8-9b7c-ecfec59210b8.png)

This error i got when i use bot nr. 4
![image](https://user-images.githubusercontent.com/41516972/44839234-87237d80-ac3e-11e8-990f-3c7b4d9b1611.png)

This error i got when i use bot nr. 6
![image](https://user-images.githubusercontent.com/41516972/44844632-bab8d480-ac4b-11e8-936f-8dfc4f0f2bca.png)

The other bots 2,3,5 works!

**Comment by DarkDoccieDutch** [comment]
The text i type when he says Write spam text: the bot don't save it into the dm_spam_text.txt file. Also when i put it manually into the .txt file the bot don't use it and only give this something went wrong error.

**Comment by DarkDoccieDutch** [comment]
i think i got it working now, only is it also possible that the bot sends more than only 1 line from the text.txt file with the dm message at once ? @Merubokkusu

**Comment by Merubokkusu** [comment]
Yeah, i'll add a feature for that once I get the time

**Comment by DarkDoccieDutch** [comment]
Great thanks i really appriciate! @Merubokkusu

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/commit/f07c5878e7bbcd8bfe0d1119582bfbac2203cb4b

Added requested feature.
