### ISSUE TITLE
Account Verification Issues

### ISSUE THREAD

**Issue by ntqueryinformation** [Merubokkusu/discord-spam-bots#71]
Not sure if this is a bug or I am just dumb, but after making the accounts, I try to verify them and i get an errors along the lines of this https://prnt.sc/vldt2e . I think its having issues connecting to the mail server. Im not sure if im supposed to make mail accounts aswell along side the discords accounts? Am i supposed to make an email for each on manually or is there any way to automate that process aswell.

**Comment by Merubokkusu** [comment]
You need to make emails for the accounts.
https://github.com/Merubokkusu/discord-spam-bots/wiki/Account-Creator

The verification process is email verification.
