### ISSUE TITLE
Error On Text Spammer

### ISSUE THREAD

**Issue by jinxx0** [Merubokkusu/discord-spam-bots#72]
OS: Win 10

**Comment by jinxx0** [comment]
File "C:\Users\lilcsz\AppData\Local\Programs\Python\Python38\lib\site-packages\discum\discum.py", line 44, in __init__
    self.__gateway_server = GatewayServer(self.__proxy_host,self.__proxy_port)
  File "C:\Users\lilcsz\AppData\Local\Programs\Python\Python38\lib\site-packages\discum\GatewayServer.py", line 35, in __init__
    self.__ws = websocket.WebSocket(sslopt={"check_hostname": False, "cert_reqs": ssl.CERT_NONE})
TypeError: __init__() got an unexpected keyword argument 'sslopt'

**Comment by Merubokkusu** [comment]
Please update discum

**Comment by jinxx0** [comment]
C:\Users\lilcsz>python -m pip install --upgrade discum
Requirement already up-to-date: discum in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (0.2.8)
Requirement already satisfied, skipping upgrade: user-agents in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from discum) (2.2.0)
Requirement already satisfied, skipping upgrade: websockets in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from discum) (8.1)
Requirement already satisfied, skipping upgrade: requests in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from discum) (2.24.0)
Requirement already satisfied, skipping upgrade: requests-toolbelt in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from discum) (0.7.0)
Requirement already satisfied, skipping upgrade: filetype in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from discum) (1.0.7)
Requirement already satisfied, skipping upgrade: random-user-agent in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from discum) (1.0.1)
Requirement already satisfied, skipping upgrade: ua-parser>=0.10.0 in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from user-agents->discum) (0.10.0)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from requests->discum) (2.10)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from requests->discum) (1.25.10)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from requests->discum) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages (from requests->discum) (2020.6.20)


???????

**Comment by Merubokkusu** [comment]
The latest version of discum is 0.3.0
Try to update again or install via git
```
git clone https://github.com/Merubokkusu/Discord-S.C.U.M.git

cd Discord-S.C.U.M

python setup.py install
```

**Comment by jinxx0** [comment]
C:\Users\lilcsz\Desktop>cd Discord-S.C.U.M-master

C:\Users\lilcsz\Desktop\Discord-S.C.U.M-master>python setup.py install
running install
running bdist_egg
running egg_info
creating discum.egg-info
writing discum.egg-info\PKG-INFO
writing dependency_links to discum.egg-info\dependency_links.txt
writing requirements to discum.egg-info\requires.txt
writing top-level names to discum.egg-info\top_level.txt
writing manifest file 'discum.egg-info\SOURCES.txt'
reading manifest file 'discum.egg-info\SOURCES.txt'
writing manifest file 'discum.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\discum
copying discum\discum.py -> build\lib\discum
copying discum\Logger.py -> build\lib\discum
copying discum\__init__.py -> build\lib\discum
copying discum\__version__.py -> build\lib\discum
creating build\lib\discum\fileparse
copying discum\fileparse\fileparse.py -> build\lib\discum\fileparse
copying discum\fileparse\__init__.py -> build\lib\discum\fileparse
creating build\lib\discum\gateway
copying discum\gateway\gateway.py -> build\lib\discum\gateway
copying discum\gateway\sessionsettings.py -> build\lib\discum\gateway
copying discum\gateway\__init__.py -> build\lib\discum\gateway
creating build\lib\discum\guild
copying discum\guild\guild.py -> build\lib\discum\guild
copying discum\guild\__init__.py -> build\lib\discum\guild
creating build\lib\discum\login
copying discum\login\Login.py -> build\lib\discum\login
copying discum\login\__init__.py -> build\lib\discum\login
creating build\lib\discum\messages
copying discum\messages\embed.py -> build\lib\discum\messages
copying discum\messages\messages.py -> build\lib\discum\messages
copying discum\messages\__init__.py -> build\lib\discum\messages
creating build\lib\discum\user
copying discum\user\user.py -> build\lib\discum\user
copying discum\user\__init__.py -> build\lib\discum\user
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\discum
copying build\lib\discum\discum.py -> build\bdist.win-amd64\egg\discum
creating build\bdist.win-amd64\egg\discum\fileparse
copying build\lib\discum\fileparse\fileparse.py -> build\bdist.win-amd64\egg\discum\fileparse
copying build\lib\discum\fileparse\__init__.py -> build\bdist.win-amd64\egg\discum\fileparse
creating build\bdist.win-amd64\egg\discum\gateway
copying build\lib\discum\gateway\gateway.py -> build\bdist.win-amd64\egg\discum\gateway
copying build\lib\discum\gateway\sessionsettings.py -> build\bdist.win-amd64\egg\discum\gateway
copying build\lib\discum\gateway\__init__.py -> build\bdist.win-amd64\egg\discum\gateway
creating build\bdist.win-amd64\egg\discum\guild
copying build\lib\discum\guild\guild.py -> build\bdist.win-amd64\egg\discum\guild
copying build\lib\discum\guild\__init__.py -> build\bdist.win-amd64\egg\discum\guild
copying build\lib\discum\Logger.py -> build\bdist.win-amd64\egg\discum
creating build\bdist.win-amd64\egg\discum\login
copying build\lib\discum\login\Login.py -> build\bdist.win-amd64\egg\discum\login
copying build\lib\discum\login\__init__.py -> build\bdist.win-amd64\egg\discum\login
creating build\bdist.win-amd64\egg\discum\messages
copying build\lib\discum\messages\embed.py -> build\bdist.win-amd64\egg\discum\messages
copying build\lib\discum\messages\messages.py -> build\bdist.win-amd64\egg\discum\messages
copying build\lib\discum\messages\__init__.py -> build\bdist.win-amd64\egg\discum\messages
creating build\bdist.win-amd64\egg\discum\user
copying build\lib\discum\user\user.py -> build\bdist.win-amd64\egg\discum\user
copying build\lib\discum\user\__init__.py -> build\bdist.win-amd64\egg\discum\user
copying build\lib\discum\__init__.py -> build\bdist.win-amd64\egg\discum
copying build\lib\discum\__version__.py -> build\bdist.win-amd64\egg\discum
byte-compiling build\bdist.win-amd64\egg\discum\discum.py to discum.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\fileparse\fileparse.py to fileparse.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\fileparse\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\gateway\gateway.py to gateway.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\gateway\sessionsettings.py to sessionsettings.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\gateway\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\guild\guild.py to guild.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\guild\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\Logger.py to Logger.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\login\Login.py to Login.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\login\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\messages\embed.py to embed.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\messages\messages.py to messages.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\messages\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\user\user.py to user.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\user\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\__init__.py to __init__.cpython-38.pyc
byte-compiling build\bdist.win-amd64\egg\discum\__version__.py to __version__.cpython-38.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying discum.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying discum.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying discum.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying discum.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying discum.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
discum.__pycache__.Logger.cpython-38: module MAY be using inspect.stack
creating dist
creating 'dist\discum-0.3.0-py3.8.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing discum-0.3.0-py3.8.egg
creating c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages\discum-0.3.0-py3.8.egg
Extracting discum-0.3.0-py3.8.egg to c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Adding discum 0.3.0 to easy-install.pth file

Installed c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages\discum-0.3.0-py3.8.egg
Processing dependencies for discum==0.3.0
Searching for websocket_client
Reading https://pypi.org/simple/websocket_client/
Downloading https://files.pythonhosted.org/packages/4c/5f/f61b420143ed1c8dc69f9eaec5ff1ac36109d52c80de49d66e0c36c3dfdf/websocket_client-0.57.0-py2.py3-none-any.whl#sha256=0fc45c961324d79c781bab301359d5a1b00b13ad1b10415a4780229ef71a5549
Best match: websocket-client 0.57.0
Processing websocket_client-0.57.0-py2.py3-none-any.whl
Installing websocket_client-0.57.0-py2.py3-none-any.whl to c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
writing requirements to c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages\websocket_client-0.57.0-py3.8.egg\EGG-INFO\requires.txt
Adding websocket-client 0.57.0 to easy-install.pth file
Installing wsdump.py script to C:\Users\lilcsz\AppData\Local\Programs\Python\Python38\Scripts

Installed c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages\websocket_client-0.57.0-py3.8.egg
Searching for random-user-agent==1.0.1
Best match: random-user-agent 1.0.1
Adding random-user-agent 1.0.1 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for user-agents==2.2.0
Best match: user-agents 2.2.0
Adding user-agents 2.2.0 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for filetype==1.0.7
Best match: filetype 1.0.7
Adding filetype 1.0.7 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for requests-toolbelt==0.7.0
Best match: requests-toolbelt 0.7.0
Adding requests-toolbelt 0.7.0 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for requests==2.24.0
Best match: requests 2.24.0
Adding requests 2.24.0 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for ua-parser==0.10.0
Best match: ua-parser 0.10.0
Adding ua-parser 0.10.0 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for six==1.15.0
Best match: six 1.15.0
Adding six 1.15.0 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for certifi==2020.6.20
Best match: certifi 2020.6.20
Adding certifi 2020.6.20 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for urllib3==1.25.10
Best match: urllib3 1.25.10
Adding urllib3 1.25.10 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for idna==2.10
Best match: idna 2.10
Adding idna 2.10 to easy-install.pth file

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect-script.py script to C:\Users\lilcsz\AppData\Local\Programs\Python\Python38\Scripts
Installing chardetect.exe script to C:\Users\lilcsz\AppData\Local\Programs\Python\Python38\Scripts

Using c:\users\lilcsz\appdata\local\programs\python\python38\lib\site-packages
Finished processing dependencies for discum==0.3.0

C:\Users\lilcsz\Desktop\Discord-S.C.U.M-master>cd C:\Users\lilcsz\Desktop\Discord-S.C.U.M-master\discord-spam-bots-master

C:\Users\lilcsz\Desktop\Discord-S.C.U.M-master\discord-spam-bots-master>python start.py
EDIT YOUR CONFIG.PY BEFORE USING!
Type one of the following numbers to launch that spammmer
       +========-Server Spammers-=========+
1 : Text Spammer - Write your own text to spam
2 : Image Spammer - Spam random images in a selected folder
3 : Insult Spammer - Picks insults online and spams them
         +========-DM Spammers-=========+
4 : Text Spammer - Write your own text to spam
5 : Image Spammer - Spam random images in a selected folder
6 : Insult Spammer - Picks insults online and spams them
           +========-Other-=========+
7 : Join Server - Join the server thats written in the config
           +========-Account Creator-=========+
8 : Account creator - Create bulk accounts
9 : Account verifier - Verify accounts
Select a bot: 1
Write spam text : test
Traceback (most recent call last):
  File "bots/server/discord_text_spam.py", line 50, in <module>
    bot = discum.Client(token=token)
  File "C:\Users\lilcsz\AppData\Local\Programs\Python\Python38\lib\site-packages\discum\discum.py", line 44, in __init__
    self.__gateway_server = GatewayServer(self.__proxy_host,self.__proxy_port)
  File "C:\Users\lilcsz\AppData\Local\Programs\Python\Python38\lib\site-packages\discum\GatewayServer.py", line 35, in __init__
    self.__ws = websocket.WebSocket(sslopt={"check_hostname": False, "cert_reqs": ssl.CERT_NONE})
TypeError: __init__() got an unexpected keyword argument 'sslopt'

**Comment by Merubokkusu** [comment]
Replace the requirements.txt with the current one.

and uninstall and reinstall discum
