### ISSUE TITLE
IndexError: list index out of range when making accounts

### ISSUE THREAD

**Issue by DirtySuN** [Merubokkusu/discord-spam-bots#74]
i was able to run the bot once fine to create an account but it created one account and went to verify the account,it didnt verify the account automatically i had to verify it manually

<img width="566" alt="Screen Shot 2020-11-28 at 5 26 50 PM" src="https://user-images.githubusercontent.com/14845087/100527262-e7e3ec80-319e-11eb-9ff8-12ad8863d085.png">

**Comment by sadoj-kuro** [comment]
same here
