### ISSUE TITLE
Bug in account creator.

### ISSUE THREAD

**Issue by GitHubMaN32** [Merubokkusu/discord-spam-bots#76]
The account creation tool doesn’t seem to work due to a error

it says 
account creator.py, line 68 in <module> create() 
account creator.py line 33 in create captcha I’d = s.post (api site) .format(api_key, site_key, url)).text split(‘|’)[1]
index error: list index out of range. 

Can anyone help?

**Comment by dsbilling** [comment]
Still having this issue? Could you provide a screenshot?
