### ISSUE TITLE
Bug with account creator

### ISSUE THREAD

**Issue by sadoj-kuro** [Merubokkusu/discord-spam-bots#77]
**Describe the bug**
when i try to use the account creator a have a error

Traceback (most recent call last):
  File "start.py", line 149, in <module>
    p = subprocess.Popen([pythonCommand,'bots/misc/account-creator/account_creator.py',enp[0],enp[1],proxy_list[proxy_number]])
IndexError: list index out of range

**To Reproduce**
1. python3 start.py
2. select 8 (account creator)

**Expected behavior**

Traceback (most recent call last):
  File "start.py", line 149, in <module>
    p = subprocess.Popen([pythonCommand,'bots/misc/account-creator/account_creator.py',enp[0],enp[1],proxy_list[proxy_number]])
IndexError: list index out of range

**Desktop (please complete the following information):**
 - OS: Debian10
 - Python Version 3.7.3

**Additional context**

**Comment by dsbilling** [comment]
Should be fixed in #80

**Comment by kekoguy** [comment]
nope its not still not working
