### ISSUE TITLE
creator account

### ISSUE THREAD

**Issue by SzumiTTV** [Merubokkusu/discord-spam-bots#79]
**Describe the bug**
When i try to generate accounts

**To Reproduce**
Traceback (most recent call last):
  File "c:/Users/user/Downloads/discord-spam-bots-master/discord-spam-bots-master/start.py", line 148, in <module>
    for combo in emailList:
NameError: name 'emailList' is not defined

**Expected behavior**
I expected it will generate account xD

**Screenshots**
![image](https://user-images.githubusercontent.com/78196019/106997596-75395380-6783-11eb-8a8c-dca6831a814a.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Python 3.8.5

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/wiki/Account-Creator
