### ISSUE TITLE
Issue with sending messages, getting repeated 401.

### ISSUE THREAD

**Issue by dbarnathan** [Merubokkusu/discord-spam-bots#81]
Using Python/Pip 3 in Linux Ubuntu.
![image](https://user-images.githubusercontent.com/54187596/107574580-dc5c6b00-6bbc-11eb-83e2-5311f68e3300.png)
I have installed all required dependencies and tried changing the post URL. All I get is 401.

Thank you.

**Comment by dbarnathan** [comment]
![image](https://user-images.githubusercontent.com/54187596/107575164-92c05000-6bbd-11eb-82aa-894132ae7062.png)
same issue on windows bash (don't mind my cmd text color)

**Comment by Merubokkusu** [comment]
Seems like an invalid token.

**Comment by dbarnathan** [comment]
![bug](https://user-images.githubusercontent.com/54187596/107588730-695def00-6bd2-11eb-9651-2fd21b98acc7.png)
Does this look like correct notation?

**Comment by dbarnathan** [comment]
'username:password,token'

**Comment by dbarnathan** [comment]
Got it, I don't read documentation apologies.
