### ISSUE TITLE
account_creator_completed.txt

### ISSUE THREAD

**Issue by KatonaCsaba** [Merubokkusu/discord-spam-bots#83]
Hey, when i try to run the start.py it says:
 File "start.py", line 21, in <module>
    account_creator_completed = open("account_creator_completed.txt", 'r+').read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: 'account_creator_completed.txt'
![startpy](https://user-images.githubusercontent.com/55943102/107717941-13be3b00-6cd5-11eb-9d57-bcf3e2f27dbb.png)

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/commit/e668a6f59e825ac549021edd686b1b812f4fbc37

Should be fixed.
