### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by alalaha** [Merubokkusu/discord-spam-bots#84]
https://prnt.sc/zdbpk6

Select a bot: 8
Starting account creation for: testtte23@gmail.com
Traceback (most recent call last):
  File "start.py", line 177, in <module>
    if(currentEmail in account_creator_completed):
TypeError: argument of type 'NoneType' is not iterable

**Comment by Merubokkusu** [comment]
fae103c redownload start.py

**Comment by alalaha** [comment]
> [fae103c](https://github.com/Merubokkusu/discord-spam-bots/commit/fae103cb91d76bf184e569ba172f4f84af4e292a) redownload start.py

new error
https://prnt.sc/zdq4v3
Select a bot: 8
Starting account creation for: testtte23@gmail.com
```
Traceback (most recent call last):
  File "start.py", line 174, in <module>
    p = subprocess.Popen([pythonCommand, 'bots/misc/account-creator/account_creator.py', enp[0], enp[1], proxy_list[proxy_number]])
IndexError: list index out of range
```

**Comment by Merubokkusu** [comment]
Using proxies?

**Comment by alalaha** [comment]
Yes

**Comment by Merubokkusu** [comment]
Strange, i've just tried it and its working.
