### ISSUE TITLE
Nothing happens after launching start.py and selecting spammer

### ISSUE THREAD

**Issue by EndLau** [Merubokkusu/discord-spam-bots#87]
**Describe the bug**
I have filled the config.py list and when I launch start.py I can see list of spammers but when I select any of them the python script just exits and nothing happens. No error message gets displayed

**To Reproduce**
1. open start.py
2. select any spammer
3. press enter

**Expected behavior**
A spammer should execute or at least show an error message if something was done incorrectly i.e. missing parameters.

**Screenshots**
https://imgur.com/a/chWh3jf

**Desktop (please complete the following information):**
OS Windows 10
Python 3.7.8

**Comment by Merubokkusu** [comment]
Can you provide the terminal output.

**Comment by Merubokkusu** [comment]
Please use latest ver
