### ISSUE TITLE
problem with bot 1

### ISSUE THREAD

**Issue by ilyanalpha** [Merubokkusu/discord-spam-bots#89]
Hello,
first of all thank you for your work.
then I would like to report that I had a small problem in using the bot indeed when I run bot 1 for text spam and enter the text in sapm it displays the following error (see screen).
is this a bot bug and did I do something wrong?
Thanks in advance for your reply.

![Capture d’écran 2021-02-24 062512](https://user-images.githubusercontent.com/76225934/108952069-4b2fce80-7669-11eb-8aa5-39a297663583.png)

**Comment by Merubokkusu** [comment]
Running proxies?

**Comment by ilyanalpha** [comment]
> Vous exécutez des proxies?

yes i use HTTP proxies

**Comment by Merubokkusu** [comment]
What’s your proxies format?

**Comment by ilyanalpha** [comment]
> Quel est votre format de proxy?

i use http prixies, I put them in proxies.txt

**Comment by Merubokkusu** [comment]
The format should look like this.
```
107.20.152.119:80
107.20.164.163:80
107.20.211.50:80
107.22.217.223:80
107.22.251.236:80
109.104.89.117:80
```

**Comment by ilyanalpha** [comment]
> The format should look like this.
> 
> ```
> 107.20.152.119:80
> 107.20.164.163:80
> 107.20.211.50:80
> 107.22.217.223:80
> 107.22.251.236:80
> 109.104.89.117:80
> ```

yes I use this format well
![proxCapture d’écran 2021-02-26 081208](https://user-images.githubusercontent.com/76225934/109267747-5e2dd480-780a-11eb-8f1c-64767e8004eb.png)

**Comment by Meteatas357** [comment]
Has anyone solved this issue? I also have the same issue.

**Comment by ilyanalpha** [comment]
> Quelqu'un a-t-il résolu ce problème? J'ai aussi le même problème.

no we have had no solution for the moment, I hope that will be settled quickly

**Comment by Merubokkusu** [comment]
f427e586c8f1589eeb6ca8e713a42a3716454515
Fixed.
