### ISSUE TITLE
Can't fill in token

### ISSUE THREAD

**Issue by siphc** [Merubokkusu/discord-spam-bots#9]
How to fill out the blank "token" in config.py ? 
I think I did this correctly but this traceback pops out

**Comment by siphc** [comment]
![image](https://user-images.githubusercontent.com/42943030/44997722-0df59480-af76-11e8-8ade-fd82a97eb6a6.png)
![image](https://user-images.githubusercontent.com/42943030/44997738-22d22800-af76-11e8-97db-2dc6f523654e.png)

**Comment by Merubokkusu** [comment]
Did you install the requirements?

**Comment by siphc** [comment]
Oh I'm sorry, I forgot the discord API. By the way am I doing it the correct way?

**Comment by Merubokkusu** [comment]
Yeah it looks fine, I'll have to make a tutorial video soon
