### ISSUE TITLE
Proxy list error on all bots.

### ISSUE THREAD

**Issue by pecatum** [Merubokkusu/discord-spam-bots#90]
Without using proxy bot says index is out of range.

![resim](https://user-images.githubusercontent.com/77746578/109388100-109e8e00-7916-11eb-83ce-2047ab0c7b6d.png)

While using proxy list;
![resim](https://user-images.githubusercontent.com/77746578/109388136-4b082b00-7916-11eb-964d-b0a62c65b571.png)
getting that error 3 times and stops.

My proxy list looks like that;
![resim](https://user-images.githubusercontent.com/77746578/109388169-79860600-7916-11eb-8437-96115c49f872.png)

And im using tokens.txt, i have tried upgrading dscum discum==1.0.0 to discum==1.0.1 nothing changed. Also installed lastests dep. 

bs4==0.0.1
discum==1.0.0 =>> discum==1.0.1
selenium==3.8.1
requests==2.21.0

nothing changes. still same error while using account creating, spam bots and joiner.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Python Version: 3.7.8

**Comment by pecatum** [comment]
And i have tried to install bot on 3 pc one of them Windows Server 2019 two of them w10 all of them got same error.

**Comment by ilyanalpha** [comment]
i have the same problem in ticket #89

**Comment by Merubokkusu** [comment]
Seems last push really messed up the start, I’ll look into it

**Comment by pecatum** [comment]
thanks mate i really grateful about your work.

**Comment by kazoomaster** [comment]
I encounter the same error :'(

**Comment by Merubokkusu** [comment]
Fixed.
f427e586c8f1589eeb6ca8e713a42a3716454515
