### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by ffredyk** [Merubokkusu/discord-spam-bots#93]
Is the bot still functional? I was trying to set it up for 4 hours with no results. The only thing I was able to fix, was the account creation logic (but I had to manually verify the e-mail links - I created bots using aliased email account - multiple emails with redirection to a single inbox). Another thing is, that the bot uses combolist.txt filled with email addresses and passwords to use during registration process - but this is not mentioned anywhere on the Wiki page here on Github, I had to figure this out myself reading the code. 

But there seems to be an issue with the server joining logic.. According to Discord API documentantion, the Invite API is meant to be used for GETting the invite link information. The bot tries to POST it with more data which returns with 401 error. According to the documentation, for a user account to be forced to join a server using API, one must supply the oAuth token and the bot has no logic to retrieve one. So the accounts won't join the server and won't spam the channel. 

Another thing is, the Discord has a rate limit for every API call the bot uses. I had to rewrite the code to be able to account for the limiting and wait between the calls to be actually able to do anything. I tried creating 20 accounts, but the original code was not able to create more than 2.

**Comment by Merubokkusu** [comment]
https://github.com/Merubokkusu/discord-spam-bots/wiki/Account-Creator

I’m a bit confused with your issues, while I haven’t updated the account creator system in awhile @DanielRTRD has.

Any rate limiting can be solved with the cool down features in the config and using proxies

You pass the token to the invite joiner through the start script

**Comment by Demo69420** [comment]
yo anyway i can contact u

**Comment by ffredyk** [comment]
> https://github.com/Merubokkusu/discord-spam-bots/wiki/Account-Creator
> 
> I’m a bit confused with your issues, while I haven’t updated the account creator system in awhile @DanielRTRD has.
> 
> Any rate limiting can be solved with the cool down features in the config and using proxies
> 
> You pass the token to the invite joiner through the start script

Okay, my bad on the wiki page, I completely somehow avoided that page 😄 

I think the proxies might be the reason it doesn't work for me, I am using a public proxylist found using google. 
I found out, that there were some changes to the account creation logic, so I downloaded the most recent clone and tried to set it up.. The bot cycled through the combolist and then killed itself, check the output:

```
F:\*****>python start.py
====
WARNING! EDIT YOUR CONFIG.PY BEFORE USING!
-=Using tokens.txt=-

====
   +=================+
Type one of the following numbers to launch that spammmer
   +========- Server Spammers -=========+
1 : Text Spammer - Write your own text to spam
2 : Image Spammer - Spam random images in a selected folder
3 : Insult Spammer - Picks insults online and spams them
   +========- DM Spammers -=========+
4 : Text Spammer - Write your own text to spam
5 : Image Spammer - Spam random images in a selected folder
6 : Insult Spammer - Picks insults online and spams them
   +========- Other -=========+
7 : Join Server - Join the server thats written in the config
   +========- Account Creator -=========+
8 : Account creator - Create bulk accounts
9 : Account verifier - Verify accounts
   +=================+
Select a bot: 8
Starting account creation for: db1@*****.cz
Starting account creation for: db2@*****.cz
Starting account creation for: db3@*****.cz
Starting account creation for: db4@*****.cz
Starting account creation for: db5@*****.cz
Starting account creation for: db6@*****.cz
Starting account creation for: db7@*****.cz
Starting account creation for: db8@*****.cz
Traceback (most recent call last):
  File "F:\*****\bots\misc\account-creator\account_creator.py", line 81, in <module>
    create()
  File "F:\*****\bots\misc\account-creator\account_creator.py", line 71, in create
    print(currentAcc, ": Discord:", r.json()['message'], 'Retry in seconds: ', r.json()['retry_after'])
KeyError: 'retry_after'
Starting account creation for: db9@*****.cz
db2 : Discord: You are being rate limited. Retry in seconds:  117033
Starting account creation for: db10@*****.cz
db3 : Discord: You are being rate limited. Retry in seconds:  112871
Starting account creation for: db11@*****.cz
db4 : Discord: You are being rate limited. Retry in seconds:  110928
Starting account creation for: db12@*****.cz
db5 : Discord: You are being rate limited. Retry in seconds:  107963
Starting account creation for: db13@*****.cz
db6 : Discord: You are being rate limited. Retry in seconds:  104982
Starting account creation for: db14@*****.cz
db7 : Discord: You are being rate limited. Retry in seconds:  101916
Starting account creation for: db15@*****.cz
db8 : Discord: You are being rate limited. Retry in seconds:  98660
Starting account creation for: db16@*****.cz
db9 : Discord: You are being rate limited. Retry in seconds:  95950
Starting account creation for: db17@*****.cz
db10 : Discord: You are being rate limited. Retry in seconds:  92387
Starting account creation for: db18@*****.cz
Starting account creation for: db19@*****.cz
db12 : Discord: You are being rate limited. Retry in seconds:  86924
Starting account creation for: db20@*****.cz
db13 : Discord: You are being rate limited. Retry in seconds:  83907
db14 : Discord: You are being rate limited. Retry in seconds:  80898
db11 : Discord: You are being rate limited. Retry in seconds:  79719
db15 : Discord: You are being rate limited. Retry in seconds:  77930
db16 : Discord: You are being rate limited. Retry in seconds:  74876
db17 : Discord: You are being rate limited. Retry in seconds:  71916
db18 : Discord: You are being rate limited. Retry in seconds:  68834
db19 : Discord: You are being rate limited. Retry in seconds:  65877
db20 : Discord: You are being rate limited. Retry in seconds:  62517

F:\*****>
```

combolist.txt
![image](https://user-images.githubusercontent.com/3717860/110982141-73f1dc80-8368-11eb-978e-74cbc5036a7c.png)

proxies.txt
![image](https://user-images.githubusercontent.com/3717860/110982246-971c8c00-8368-11eb-9568-d93df7318205.png)

tokens.txt
![image](https://user-images.githubusercontent.com/3717860/110982356-badfd200-8368-11eb-89b3-eeaf89dcf205.png)

The tokens.txt file was automatically generated using previous version of the bot.

When I try to run the server join logic, following error shows up:
![image](https://user-images.githubusercontent.com/3717860/110982657-17db8800-8369-11eb-8e26-6850f384c341.png)

**Comment by Merubokkusu** [comment]
Sorry for the late response, public proxies don't work with discord.

**Comment by Demo69420** [comment]
> Sorry for the late response, public proxies don't work with discord.

Yo could I pay u to make me a simple mass report bot for discord servers like this one or just one that works: https://youtu.be/ETuIHRCCQtw I'll pay as much as u want
