### ISSUE TITLE
Accounts instantly get banned

### ISSUE THREAD

**Issue by GoatInAHat** [Merubokkusu/discord-spam-bots#96]
I created an alt, verified the phone number and email, and left all the settings that weren't required on their default values, and ran the dm spam bot. It dmed two people, then the account got banned. Is this because I had the account open in a chrome tab while it was running or is this a known issue that there is an easy fix to?

**Comment by Merubokkusu** [comment]
Getting banned is usually due to sending the same message over again.

**Comment by Merubokkusu** [comment]
also it’s best practice to use non-public  proxies

**Comment by GoatInAHat** [comment]
> Getting banned is usually due to sending the same message over again.

I got banned after only sending one message

**Comment by Merubokkusu** [comment]
Any way to provide a video example? 

Has this happened more than once
